language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler:
        - clang
        - gcc
    - os: osx
      compiler:
        - clang
        - gcc

script:
  - cmake -D CMAKE_CXX_COMPILER=$CXX CMakeLists.txt

after_script:
  - make
