language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: osx
      compiler: clang

script:
  - cmake -D CMAKE_CXX_COMPILER=$CXX CMakeLists.txt

after_script:
  - make
