language: cpp

compiler:
  - clang
  - gcc

before_install:
  - brew install cmake

script:
  - echo $CXX
  - $CXX --version
  - cmake -D CMAKE_CXX_COMPILER=$CXX CMakeLists.txt

after_script:
  - make
